# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: bruce.mcintyre@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://bruskiza.github.io"
twitter_username: bruskiza
github_username:  bruskiza
facebook_username:  bruskiza

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
